steps:
 - name: ":hammer: build image"
   command: .buildkite/steps/build.sh
   label: ":singularity: ${PROJECT:-feelpp-toolboxes} singularity bootstrap"
   agents:
     singularity: true
   env:
     PROJECT: "${PROJECT:-feelpp-toolboxes}"
     TAG: "${TAG:-develop}"
     GIRDER_ID: "${GIRDER_ID:-\"5a4fa90ab0e9571f842931e5\"}"
     SREGISTRY_COLLECTION: "${SREGISTRY_COLLECTION:-mso4sc}"
