steps:
 - name: ":hammer: Generate recipe"
   command: .buildkite/steps/recipe.sh
   label: ":singularity: ${PROJECT:-feelpp-toolboxes} singularity bootstrap"
   agents:
     singularity: true
   env:
     PROJECT: "${PROJECT:-feelpp-toolboxes}"
     TAG: "${TAG:-develop}"
     GIRDER_ID: "${GIRDER_ID:-\"5a4fa90ab0e9571f842931e5\"}"
 - wait
 - name: ":hammer: Generate image"
   command: .buildkite/steps/image.sh
   label: ":singularity: ${PROJECT:-feelpp-toolboxes} singularity images"
   agents:
     singularity: true
   env:
       BUILDKITE_GIT_CLEAN_FLAGS: "-fdq"
       PROJECT: "${PROJECT:-feelpp-toolboxes}"
       TAG: "${TAG:-develop}"
       GIRDER_ID: "${GIRDER_ID:-\"5a4fa90ab0e9571f842931e5\"}"
 - wait
 - name: ':rocket: Deploy ${PROJECT:-feelpp-toolboxes} images'
   command: .buildkite/steps/push.sh
   agents:
     singularity: true
   env:
       BUILDKITE_GIT_CLEAN_FLAGS: "-fdq"
       PROJECT: "${PROJECT:-feelpp-toolboxes}"
       TAG: "${TAG:-develop}"
       GIRDER_ID: "${GIRDER_ID:-\"5a4fa90ab0e9571f842931e5\"}"
