steps:
 - name: ":hammer:Generate bootstrap"
   command: .buildkite/steps/bootstrap.sh
   label: ":singularity: Feel++ singularity bootstrap"
   agents:
     singularity: true
 - wait
 - name: ":hammer:Generate images"
   command: .buildkite/steps/images.sh
   label: ":singularity: Feel++ singularity images"
   agents:
     singularity: true
 - wait
 - name: ':rocket: Deploy images'
   command: .buildkite/steps/push.sh
   agents:
     singularity: true
